### ISSUE TITLE
Error when attempting to start

### ISSUE THREAD

**Issue by Boso101** [jeromew21/hearthstonelike#1]
![image](https://user-images.githubusercontent.com/22697660/44252130-54d75080-a23a-11e8-835d-9b78e62ddba2.png)

Windows 10 Powershell Python 3.7.0

**Comment by jeromew21** [comment]
Oh, I think I forgot to pack the wrapper I wrote for Pygame in the repo, thanks for pointing this out haha

**Comment by jeromew21** [comment]
Should be fixed

**Comment by Boso101** [comment]
No problem, yep fixed now :)
